server:
  port: 8083

  ssl:
    key-store: classpath:javaboy.p12
    key-alias: tomcathttps
    #    配置密码，就是在生成证书的时候输入的密码
    key-store-password: 123456


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login?serverTimezone=GMT%2B8
    username: root
    password: 19990807
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:content-type: text/html
    mode: HTML5
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates

    #文件大小 MB必须大写
    #  maxFileSize 是单个文件大小
    #  maxRequestSize是设置总上传的数据大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath*:mapper/*.xml


redis:
    database:  0
    host:  127.0.0.1
    port:  6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0


user:
  name: zhu
  address: sasa